feat: add "Add to Google Calendar" for virtual contests
kenkoooo/AtCoderProblems pull request #1058
Opened 2021-09-05 07:42 UTC by southball

Resolves #1055.

## やったこと

バーチャルコンテストのページで、コンテストが終わってないなら「Add to Google Calendar」のボタンを追加しました。

## スクリーンショット

![Screenshot of virtual contest detail page](https://user-images.githubusercontent.com/6523469/132119343-dce93919-7279-4d62-9a62-80d76ea3f0f3.png)
![Screenshot of event creation page in Google Calendar](https://user-images.githubusercontent.com/6523469/132119321-6e400fab-75ba-4ee6-bd00-bc4e0371cbfa.png)

2021-09-05 11:26 UTC, kenkoooo requested changes
全体的に良い感じです！ありがとうございます！

2021-09-05 11:26 UTC, kenkoooo commented on atcoder-problems-frontend/src/components/GoogleCalendarButton.tsx
> +  children: React.ReactNode;
今のところはこのボタンは「バチャを Google Calendar に追加する」機能しか要らないので、今は `color` と `children` はサポートしないで良さそうです。

2021-09-05 11:26 UTC, kenkoooo commented on atcoder-problems-frontend/src/components/GoogleCalendarButton.tsx
> +  id: string;
`contestId` とかにすると何の id か分かりやすくなって良いかもしれません。

2021-09-05 11:26 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/index.tsx
> +            {now < end ? (
`now < end && (...)` とかにすると `null` を明記しなくても良くなりそうです。

2021-09-05 15:34 UTC, southball commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/index.tsx
> +            {now < end ? (
同じファイルで `bool ? <Component /> : null` のパターンがいくつかあるけど、これだけ修正しても大丈夫でしょうか。

2021-09-05 15:34 UTC, southball commented on atcoder-problems-frontend/src/components/GoogleCalendarButton.tsx
> +  children: React.ReactNode;
ありがとうございます。消しました。

2021-09-05 15:35 UTC, southball commented on atcoder-problems-frontend/src/components/GoogleCalendarButton.tsx
> +  id: string;
名前を変えました！

2021-09-05 17:10 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/index.tsx
> +            {now < end ? (
はい、これだけで大丈夫です！（もちろん他のも修正してしまってもOKです）

2021-09-05 17:10 UTC, kenkoooo commented on atcoder-problems-frontend/src/components/GoogleCalendarButton.tsx
> +  id: string;
👍

2021-09-06 15:27 UTC, southball commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ShowContest/index.tsx
> +            {now < end ? (
ありがとうございます！同じファイルで全く同じパターンのコードも一応修正しました。

2021-09-06 15:35 UTC, kenkoooo approved these changes

2021-09-08 13:07 UTC, merged