ContestUpdatePageをswr で置き換える
kenkoooo/AtCoderProblems pull request #1074
Opened 2021-11-02 09:22 UTC by atsuya02

2021-11-02 09:32 UTC, atsuya02 commented
@kenkoooo 
確認よろしくお願いします。

2021-11-02 10:00 UTC, atsuya02 commented
申し訳ありません、不備を見つけました。
修正します。

2021-11-05 08:02 UTC, atsuya02 commented
@kenkoooo 
質問があります。
`updateResponse`をswrで置き換える際に
```
export const useContestUpdate = () => {
  return useSWRData(`${BASE_URL}/contest/update`, (url) =>
    typeCastFetcher<unknown | null>(url)
  );
};
```
という実装をすると
<img width="552" alt="image" src="https://user-images.githubusercontent.com/73219274/140475468-34a8839c-fe8a-4a3a-bb2b-2ec9992ecb80.png">
というエラーが出てしまいます。

質問として、
- 上の`useSWRData`のurlが間違っているのでしょうか？
- それとも実装方法が間違っているのでしょうか？

2021-11-05 08:19 UTC, kenkoooo commented
たぶんissueでの説明不足のせいで認識の齟齬があるみたいです。すみません。分からないところがあったらどんどん聞いてください。

SWRはユーザーの受動的なリクエストの用途にしか向いていません。具体的にはページを開いた時に送るGETリクエストのことです。なので、コンテスト一覧を表示したり、コンテストの情報を取得したりする際にはSWRを使います。

それ以外のユーザーの能動的なリクエスト、このサイトではユーザーが情報を更新するために送るPOSTリクエストのことですが、これには普通に `fetch` を使います。これらは下記のファイルにまとまっているので、見てみてください。
https://github.com/kenkoooo/AtCoderProblems/blob/0282bbde17f6b5628f3bb366fef2ac8cb2fca5f0/atcoder-problems-frontend/src/pages/Internal/VirtualContest/ApiClient.ts

2021-11-05 09:39 UTC, atsuya02 commented
@kenkoooo 
ありがとうございます。
実装の方終わりました、確認お願いします。

https://user-images.githubusercontent.com/73219274/140490141-a0bb8a63-b19b-419b-b553-f6dd7cc4d3e4.mov

2021-11-06 10:02 UTC, kenkoooo requested changes
ありがとうございます！良さそうです！細かいところをいくつかコメントしました。

2021-11-06 10:02 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ContestUpdatePage.tsx
> +export const ContestUpdatePage = (props: OuterProps) => {
`InnerProps` がいなくなったので `OuterProps` は `Props` にしてしまって良さそうです。

2021-11-06 10:02 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ContestUpdatePage.tsx
> +  const [updateResponse, setUpdateResponse] = React.useState<number>();
「更新済みかどうか？」を表す値なので boolean で良さそうです。

2021-11-07 10:16 UTC, atsuya02 commented
@kenkoooo 
修正終わりました。

2021-11-07 10:31 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/Internal/VirtualContest/ContestUpdatePage.tsx
> +  const [updateResponse, setUpdateResponse] = React.useState<boolean>();
気持ち的に初期値が設定されていると嬉しいです。

2021-11-07 10:39 UTC, atsuya02 commented
@kenkoooo 
丁寧にレビューしていただきありがとうございます！
修正終わりました。

2021-11-11 12:26 UTC, kenkoooo approved these changes
良さそうです！近日中にマージしてリリースします！

2021-11-12 14:09 UTC, merged