ContestProblem に problem_index を追加する
kenkoooo/AtCoderProblems pull request #1110
Opened 2022-01-06 16:31 UTC by southball

Fixes #936.

ATC002 のアルファベットが正しく表示できるところまで実装しました。
<img width="878" alt="atc002_screenshot" src="https://user-images.githubusercontent.com/6523469/148414917-5a85eddc-d99a-45ba-ae94-ffc65ccfa5e5.png">

一つ確認したいことがありますが、#936 で
> クローラーが問題インデックスを問題名に含めないようにする。  

とおっしゃいましたが、それをまだ実装していません。

実装すると API の `problems.json` および `contest-problems.json` の `title` から問題インデックスが消されるけどそれも大丈夫ですか。（他にこの API を使ってるユーザーのことをちょっと考えています。）

念のため Table ページのフルページスクリーンショットを取っておきましたので上げておきます。 [AtCoderProblems_Table_Screenshots.zip](https://github.com/kenkoooo/AtCoderProblems/files/7823306/AtCoderProblems_Table_Screenshots.zip)

2022-01-07 02:26 UTC, kenkoooo commented
> 実装すると API の problems.json および contest-problems.json の title から問題インデックスが消されるけどそれも大丈夫ですか。（他にこの API を使ってるユーザーのことをちょっと考えています。）

おしゃるとおり、backward-incomatible cahnge なので、以下のように考えてはどうでしょう？

- `title` の中身は変えない。
- 新しく `position` と `name` を追加する。
- 移行期間を設けて、その間は `{ id:string, title:string, name:string, position:string }` がレスポンスになるようにする。
- 移行期間が終わったら `title` を削除する。

2022-01-07 16:56 UTC, southball commented
`problems.json`（および `merged-problems.json`）に `position` と `name` を追加する方針で問題ないと思われます。その方針で実装していきたいと思います。

もう一つだけ確認したいですが、`contest-problems.json` に追加された `problem_index` に `position` と同じような内容が入っていますが、名前を一致させますか。（なお同じ Problem に対して `position` は一個しかないが、同じ `problem_id` の ContestProblem の `problem_index` は contest ごとに変わります）

2022-01-08 15:49 UTC, kenkoooo commented
名前はお任せします（ `position` とか適当に考えたやつなので）

2022-01-14 14:48 UTC, southball commented
ご連絡してなくてすみません。

バックエンドに `problem_index` と `name` を追加して、確認してるとき `problems.json` の `contest_id` が今の値と違ってデバッグが必要のと、フロントエンドで `title` を使っているところを全部 `problem_index` と `name` に置き換える必要があるので少し時間がかかりますが、最近タスクが多くて手が回らないです。着手できるのが月末になると思いますので、時間があったら着手します。

実装が終わったらまたコメントします。

2022-01-15 06:53 UTC, kenkoooo commented
時間があるときで全然大丈夫です！僕も仕事が爆発炎上してるので、中々手が回らず…

2022-02-03 08:11 UTC, southball commented
たぶんこれで修正しました。  
お時間のあるときちょっと確認してもらえるとありがたいです。

2022-03-05 09:18 UTC, kenkoooo requested changes
良さそうです！フロントエンドの integration test を見てもらっても良いですか？

2022-03-05 15:42 UTC, southball commented
おそらくマージする前のこのプルリクの frontend の integration test が通らないので、新しい backend を使っていくつかの static ファイルを生成して、integration test が問題なく通ることを確認しました。

- このコミットから確認できます：https://github.com/southball/AtCoderProblems/commit/a10ecb93aedd9c9fa8c20b6a5bfc70139307882b
    - フロントエンドの GitHub Action: https://github.com/southball/AtCoderProblems/runs/5433598328
- 動作確認用：https://public.southball.dev/atcoder-a10ecb9/#/table/
- 生成したファイル：
    - https://public.southball.dev/contest-problem.json
    - https://public.southball.dev/contests.json
    - https://public.southball.dev/merged-problems.json
    - https://public.southball.dev/problems.json

2022-03-15 10:04 UTC, southball commented
Review request 押し忘れた気がします...

2022-03-16 07:30 UTC, kenkoooo commented
あ、すみません、認識はしていたのですが、時間が取れず…

2022-03-17 00:13 UTC, southball commented
すみません、ご時間のあるとき確認していただいて結構です。

2022-04-10 09:43 UTC, merged