Add "AC during/after Contest" filter for ListTable
kenkoooo/AtCoderProblems pull request #781
Opened 2020-08-25 13:56 UTC by iilj

- ListTable において，コンテスト中の AC／コンテスト後のACのみを絞り込めるようにします．
- コンテスト中にACした最高 difficulty 付近の問題を公表するというのが Twitter で若干流行っているので，使途はありそうです．
![image](https://user-images.githubusercontent.com/59337901/91182665-6b67ea80-e725-11ea-8b53-252c84ffa5de.png)

2020-08-25 15:02 UTC, kenkoooo requested changes

2020-08-25 15:02 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +    | "AC after Contest";
これだけ増えてきましたし、StatusFilter の型をimportした方が良さそうです。

2020-08-25 15:02 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +              );
これは無理に1行にまとめないで変数を置いても良いと思います。

2020-08-25 16:34 UTC, iilj commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +    | "AC after Contest";
以下のあたりのポリシーを確認したいです．

- `StatusFilter` は現状では ListPage/Index.tsx 内で定義されていますが，これをそのまま export して ListTable.tsx に import するというのは，参照は循環していませんが import 先が循環しているため，若干気持ち悪い感じがします．
  - （個人的には，このような状態は避けていますが，正しく動作はするはずなので，AtCoder Problems のポリシー的に OK なら大丈夫です．）
- そこで，`StatusFilter` の定義を ListTable.tsx 内に移すことを考えています．その場合，ListTable.tsx で `statusFilters` あるいは `convertToValidStatusFilterState` のいずれかを export することになるかと思います．私としては前者（`statusFilters` の export）のほうが良さそうな気がしていますが，いかがでしょう．
  - 前者のほうが良さそうと思うのは，`convertToValidRatedFilter` と同じく `convertToValidStatusFilterState` は ListPage/Index.tsx 内固有の手続きなので，ListTable.tsx 内に定義するのは微妙と感じるためです．

2020-08-25 17:07 UTC, iilj commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +              );
変数を使うわけではありませんが，以下のようにするのはどうでしょう．

```js
case "AC during Contest":
  if (row.status.label !== StatusLabel.Success || row.contest === undefined) return false;
  return row.status.epoch <= row.contest.start_epoch_second + row.contest.duration_second;
case "AC after Contest":
  if (row.status.label !== StatusLabel.Success) return false;
  if (row.contest === undefined) return true;
  return row.status.epoch > row.contest.start_epoch_second + row.contest.duration_second;
```

---

元のコードの当該部分は，

- 406 行目の `status.label === StatusLabel.Success` によって `status.epoch !== undefined` が担保される
- 407 行目の `contest !== undefined` によって `start_epoch_second`, `duration_second` が使えるようになる

のようなつくりになっています．変数を置いてスッキリさせようとしても，事前に上記チェックを経ないと epoch の計算ができないので，なんだか（私が書くと）冗長になってしまいます．

あえて変数を使うということであれば，以下のような書き方はできますが，綺麗ではないです．

```js
case "AC during Contest": {
  if (row.status.label !== StatusLabel.Success || row.contest === undefined) return false;
  const end_epoch_second = row.contest.start_epoch_second + row.contest.duration_second;
  return row.status.epoch <= end_epoch_second;
}
case "AC after Contest": {
  if (row.status.label !== StatusLabel.Success) return false;
  if (row.contest === undefined) return true;
  const end_epoch_second = row.contest.start_epoch_second + row.contest.duration_second;
  return row.status.epoch > end_epoch_second;
}
```

2020-08-26 07:26 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +    | "AC after Contest";
ポリシーについては僕は知らないので何とも言えませんが、多分どちらでも良いと思います。個人的には import が循環するのはメンテナンス性の観点からもあまり良く無さそうなので、書いていただいた通り `ListTable.tsx` に移したり、`ListPage/types.ts` みたいのを作って入れたりするのが良さそうと思います。`convertToValidStatusFilterState` は `StatusFilter` の public static method みたいなものなので、これを export することには特に抵抗がないです。これもどちらでも良いと思います。

2020-08-26 07:53 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +              );
綺麗かどうかを判断する能力が無いので的外れなことを言っていたら申し訳ないのですが、他の人や自分が後で見た時に意味を理解しやすい (understanding / sec が高い) 方が良いと思います。

例えば `"AC during Contest"` であれば `if(コンテスト中 && AC) return true;` したいはずなので、`switch` の前で `isSubmittedInContest` （もっとシンプルな名前で良いと思います）みたいな変数を作っておけば、

```js
case "AC during Contest": {
   return row.status.label === StatusLabel.Success && isSubmittedInContest;
}
case "AC after Contest": {
   return row.status.label === StatusLabel.Success && !isSubmittedInContest;
}
```

みたいな感じに書けると思います。
（`row.status.label === StatusLabel.Success` も変数にしちゃっていいと思います）

2020-08-26 09:17 UTC, iilj commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +              );
> 他の人や自分が後で見た時に意味を理解しやすい (understanding / sec が高い) 方が良い

> `row.status.label === StatusLabel.Success` も変数にしちゃっていいと思います

これらの点に関しては同意です．

その上で，`status.epoch` と `contest.start_epoch_second` と `contest.duration_second` が `number` であることを assert しないと `isSubmittedInContest` を求められないので，ひとまずはこんな感じでしょうか．

```js
const { status, contest } = row;
const isSuccess = status.label === StatusLabel.Success;
const isSubmittedInContest = status.label === StatusLabel.Success
  && contest !== undefined
  && status.epoch <= contest.start_epoch_second + contest.duration_second;
switch (props.statusFilterState) {
  // ...
}
```

問題なさそうであれば，これでいきます．

2020-08-26 13:09 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +              );
いいと思います

2020-08-27 03:52 UTC, iilj commented
直してみました．いかがでしょう．

2020-08-27 14:19 UTC, merged