add URL parameter to sort list table.
kenkoooo/AtCoderProblems pull request #812
Opened 2020-10-31 00:34 UTC by t-mangoe

#786 のissueについてのプルリクです。
URLパラメーターでListTableをソートできるように実装してみました。

2020-10-31 08:23 UTC, kenkoooo requested changes

2020-10-31 08:23 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/index.tsx
> +  const sortOrder = searchParams.get("sortOrder") || "desc";
```suggestion
  const sortOrder = searchParams.get("sortOrder") === "asc" ? "asc" : "desc";
```

2020-10-31 08:23 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/ListPage/ListTable.tsx
> +  sortOrder: any;
```suggestion
  sortOrder: "asc" | "desc";
```

2020-11-01 01:24 UTC, t-mangoe commented
レビュー、ありがとうございます。
修正しました。

2020-11-02 06:33 UTC, merged