Userid case insensitive
kenkoooo/AtCoderProblems pull request #828
Opened 2020-12-17 01:40 UTC by uya116

issuesの[User IDs should be case-insensitive](https://github.com/kenkoooo/AtCoderProblems/issues/113)に対応しました。

- データを再クロールしなくても良いようにget時のSQLマッチング部分を変更しています。

2020-12-17 03:18 UTC, kenkoooo commented on atcoder-problems-backend/sql-client/src/submission_client.rs
> +                    WHERE LOWER(user_id) = LOWER($1)
`WHERE user_id = $1` のときは `user_id` にインデックスがあるのである程度高速でしたが、この実装では既存のインデックスは効かなくなりますか？

2020-12-17 04:58 UTC, uya116 commented on atcoder-problems-backend/sql-client/src/submission_client.rs
> +                    WHERE LOWER(user_id) = LOWER($1)
確かにそうですね。この実装だと新たにLOWER(user_id)でインデックスを貼っていただく必要があります。

2020-12-27 13:11 UTC, kenkoooo commented on atcoder-problems-backend/sql-client/src/submission_client.rs
> +                    WHERE LOWER(user_id) = LOWER($1)
DBスキーマの方も更新していただいて良いですか？
https://github.com/kenkoooo/AtCoderProblems/blob/master/config/database-definition.sql

2020-12-28 00:49 UTC, uya116 commented
DBスキーマ更新しました。ご確認よろしくお願い致します:pray:

2020-12-29 17:20 UTC, kenkoooo approved these changes
良さそうです。時間のある時にマージ・デプロイします。

2020-12-30 16:05 UTC, kenkoooo requested changes
すみません、`LOWER()` での比較について、インデックス作成後に調べてみたのですが、どうも `LOWER` 無しの時に比べて悪くなっているように見えます。

```
atcoder=> EXPLAIN SELECT * FROM submissions WHERE user_id='kenkoooo';
                                       QUERY PLAN                                        
-----------------------------------------------------------------------------------------
 Bitmap Heap Scan on submissions  (cost=25.10..2299.09 rows=586 width=77)
   Recheck Cond: ((user_id)::text = 'kenkoooo'::text)
   ->  Bitmap Index Scan on submissions_user_id_idx  (cost=0.00..24.96 rows=586 width=0)
         Index Cond: ((user_id)::text = 'kenkoooo'::text)
(4 rows)

atcoder=> EXPLAIN SELECT * FROM submissions WHERE LOWER(user_id)=LOWER('kenkoooo');
                                        QUERY PLAN                                         
-------------------------------------------------------------------------------------------
 Bitmap Heap Scan on submissions  (cost=1818.63..192295.08 rows=86460 width=77)
   Recheck Cond: (lower((user_id)::text) = 'kenkoooo'::text)
   ->  Bitmap Index Scan on submissions_lower_idx  (cost=0.00..1797.01 rows=86460 width=0)
         Index Cond: (lower((user_id)::text) = 'kenkoooo'::text)
(4 rows)
```

2021-01-01 14:31 UTC, uya116 commented
ありがとうございます:pray: 時間のあるときに検討します！

2021-01-04 00:21 UTC, uya116 commented
現象として[このページ](https://use-the-index-luke.com/ja/sql/where-clause/functions/case-insensitive-search)の
> 行数の見積もりが大きすぎるのです

が発生している気がします。
同ページの
> 統計情報の更新

を実施してみていただけませんでしょうか？

2021-01-05 10:52 UTC, kenkoooo commented
`ANALYZE submissions;` を実施することで、PostgreSQL の統計情報を更新することができました。これによって `EXPLAIN` の情報が更新され、`LOWER` を入れても同等のパフォーマンスで取得できることがわかりました。
```
atcoder=> explain select * from submissions WHERE user_id='kenkoooo';
                                       QUERY PLAN                                        
-----------------------------------------------------------------------------------------
 Bitmap Heap Scan on submissions  (cost=25.23..2360.23 rows=602 width=77)
   Recheck Cond: ((user_id)::text = 'kenkoooo'::text)
   ->  Bitmap Index Scan on submissions_user_id_idx  (cost=0.00..25.08 rows=602 width=0)
         Index Cond: ((user_id)::text = 'kenkoooo'::text)
(4 rows)

Time: 0.681 ms
atcoder=> explain select * from submissions WHERE LOWER(user_id)='kenkoooo';
                                      QUERY PLAN                                       
---------------------------------------------------------------------------------------
 Bitmap Heap Scan on submissions  (cost=13.23..2349.73 rows=602 width=77)
   Recheck Cond: (lower((user_id)::text) = 'kenkoooo'::text)
   ->  Bitmap Index Scan on submissions_lower_idx  (cost=0.00..13.08 rows=602 width=0)
         Index Cond: (lower((user_id)::text) = 'kenkoooo'::text)
(4 rows)

Time: 0.660 ms
atcoder=> 
```

2021-01-05 10:52 UTC, kenkoooo approved these changes

2021-01-05 10:52 UTC, merged