問題カテゴリ別の達成度を表示
kenkoooo/AtCoderProblems pull request #992
Opened 2021-06-20 09:01 UTC by penicillin0

## ref
https://github.com/kenkoooo/AtCoderProblems/issues/909

2021-06-27 04:36 UTC, penicillin0 commented
カテゴリ別にステータスの取得までできました。
PieChartで表示できるようしていきます([ref](https://github.com/kenkoooo/AtCoderProblems/issues/909#issuecomment-867686944))

<img src="https://user-images.githubusercontent.com/56141035/123532932-8859b980-d74c-11eb-9a05-05c1e215ee36.png" width="640px">

2021-06-27 09:02 UTC, penicillin0 commented on atcoder-problems-frontend/src/interfaces/ContestCategory.ts
> +export type ContestCategory = typeof ContestCategories[number];
複数箇所で使うことになるので、共通化しました。

2021-06-27 09:06 UTC, penicillin0 commented
![image](https://user-images.githubusercontent.com/56141035/123538981-58251180-d772-11eb-8f82-08f8ed27a853.png)

2021-06-28 05:14 UTC, kenkoooo commented on atcoder-problems-frontend/src/interfaces/ContestCategory.ts
> +export type ContestCategory = typeof ContestCategories[number];
ContestClassifier と密接なものなので、別々の場所にあるのは違和感があります。

2021-06-30 08:43 UTC, penicillin0 commented on atcoder-problems-frontend/src/interfaces/ContestCategory.ts
> +export type ContestCategory = typeof ContestCategories[number];
@kenkoooo 
型なので、`interfaces`にあった方が良いのかな程度の考えでした。

ですと、
- `/utils/ContestClassifier.ts`にまとめる
- `ContestCategory.ts`にまとめる

だとどちらが良いでしょう？

2021-06-30 09:59 UTC, penicillin0 commented on atcoder-problems-frontend/src/interfaces/ContestCategory.ts
> +export type ContestCategory = typeof ContestCategories[number];
@kenkoooo 
なるほどです。
現状の構成にする場合、`pages/UserPage/CategoryPieChart/index.ts`から`pages/TablePage/ContestClassifier.ts`を使う形になりますが、問題ないですか？

2021-06-30 10:22 UTC, kenkoooo commented on atcoder-problems-frontend/src/interfaces/ContestCategory.ts
> +export type ContestCategory = typeof ContestCategories[number];
すみません、`ContestClassifier` が既に `/utils` にいると誤認していました。おっしゃる通り `/utils` に移しましょうか。

2021-06-30 10:53 UTC, penicillin0 commented on atcoder-problems-frontend/src/interfaces/ContestCategory.ts
> +export type ContestCategory = typeof ContestCategories[number];
@kenkoooo 
対応しました。
再度確認お願いします。

2021-06-30 11:16 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +        titleStatus.titleStatus.map((problemStatuses) => {
`map` ではなく `forEach` ですか？

2021-06-30 11:19 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +      const contest = contests?.find((c) => c.id === titleStatus.contestId);
（多分問題ないですが）この部分でコンテスト数について線形時間かかっているのがやや気になります。

2021-06-30 11:22 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +    ([contestTitle, problems]) => {
`Contest` は `title` と `id` を別に持っていて、これは `id` なので、そのように rename していただけますか？

2021-06-30 11:25 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +      if (category !== undefined) {
`category` が undefined になるのって `contest` が undefined のときだけのはずなので、もっと早い段階で filter できそうな気がします。

2021-06-30 11:26 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +    }))
`Map<ContestCategory, {solved, rejected, total}>` で良さそうな気がします

2021-06-30 13:04 UTC, penicillin0 commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +      const contest = contests?.find((c) => c.id === titleStatus.contestId);
`contests `を`Map<string, Contest>`で持つことにしました。

2021-06-30 13:06 UTC, penicillin0 commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +    return counts;
@kenkoooo 
> Map<ContestCategory, {solved, rejected, total}> で良さそうな気がします

カテゴリのカウントを連想配列からMapにして見たんですが、少し無理やりな感じになってしまいました。
もっとうまく書けますかね...

2021-06-30 13:08 UTC, penicillin0 commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
@kenkoooo 
> Map<ContestCategory, {solved, rejected, total}> で良さそうな気がします

カテゴリのカウントを連想配列からMapにして見たんですが、少し無理やりな感じになってしまいました。
もっとうまく書けますかね...

2021-06-30 13:37 UTC, penicillin0 commented
@kenkoooo 

ご指摘いただいた点の修正完了しました、確認お願いします。
(メンション付けたり消したりごめんなさいmm)

2021-07-01 08:32 UTC, kenkoooo requested changes

2021-07-01 08:32 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +  const titleStatuses = Array.from(contestToProblems).map(
title ではなくなったかと思います

2021-07-01 08:32 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +  const titleStatuses = Array.from(contestToProblems).map(
statusByContest とかですかね

2021-07-01 08:32 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +    const contest = contestMap.get(titleStatus.contestId);
ここで contest を取得していますが、その前の statuses  を作る段階で採ってしまったほうが良いのではないかと思います。

2021-07-01 12:54 UTC, penicillin0 commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +    const contest = contestMap.get(titleStatus.contestId);
statuses を作る段階でcontestを取得し、この段階で`undefine`もfilterするようにしました。

2021-07-01 14:43 UTC, kenkoooo requested changes
ありがとうございます。全体的に良さそうです。もしよければ、hookやReact.Element以外の計算部分だけ関数に切り出してテストを書いていただけますか？

2021-07-02 09:35 UTC, penicillin0 commented
@kenkoooo 
`ContestClassifier`, `CategoryPieChart/index.tsx`のテストを追加しました。
手元では全てのテスト通ったことを確認しました。

確認よろしくお願いします。

2021-07-02 09:59 UTC, kenkoooo requested changes

2021-07-02 09:59 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.tsx
> +
ここの部分のhook以外の部分を切り出して1つの関数に切り出して期待した `categoryCounts` が取得できるかどうかのテストを書いていただいても良いですか？

2021-07-03 09:16 UTC, penicillin0 commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.test.ts
> +  });
@kenkoooo 
こういうことであっていますでしょうか？

2021-07-03 10:44 UTC, kenkoooo commented on atcoder-problems-frontend/src/pages/UserPage/CategoryPieChart/index.test.ts
> +  });
はい、ありがとうございます。

2021-07-03 10:45 UTC, kenkoooo approved these changes

2021-07-03 15:20 UTC, merged

2022-06-02 06:28 UTC, maspypy commented
Category Piles の、総問題数、AC数なのですが、同じ問題が複数回数えられています。
これを unique することは可能でしょうか？
カテゴリ区分のない場合のAC数と基準が整合していると嬉しいです。
（複数のカテゴリに入っている問題があるため、単純に足し算しても合わないのは分かります）